### ISSUE TITLE
Version kc-11-b2 has problems with JPA

### ISSUE THREAD

**Issue by turlarion** [Captain-P-Goldfish/scim-for-keycloak#18] opened 2021-07-20 12:03 UTC
Found bug in kc-11-b2. Tab SCIM doesn't open and shows error. In logs found an error like "org.keycloak.models.ModelException: java.lang.IllegalArgumentException: Type specified for TypedQuery [de.captaingoldfish.scim.sdk.keycloak.entities.ScimServiceProviderEntity] is incompatible with query return type [class de.captaingoldfish.scim.sdk.keycloak.entities.ScimServiceProviderEntity]". After debugging code found out that it appears in de.captaingoldfish.scim.sdk.keycloak.services.ScimServiceProviderService on line 190. @Captain-P-Goldfish What should i do to fix it?

**Comment by Captain-P-Goldfish** [comment] 2021-07-20 16:18
I just checked and I cannot reproduce this behaviour. In this case the following things would be interesting for me:

1. complete StackTrace of the Exception
2. the database in use (version and database vendor)

**Comment by Captain-P-Goldfish** [comment] 2021-08-03 16:11
is this still a problem or can I close this ticket?

**Comment by turlarion** [comment] 2021-08-03 17:02
No, sorry, the problem solved itself

**Closed** 2021-08-03 17:10 UTC
